version: '3'

networks:
  admin_network:

services:

  ##########
  # Admin #
  ##########

  # App container
  admin_app:
    build: admin-app
    hostname: admin-app
    volumes:
      - ./admin-app/app:/code/admin-app:cached
    networks:
      - admin_network
    depends_on:
      - cache
      - redis
      - db

  ##########
  # Common #
  ##########

  # Nginx webserver
  nginx:
    image: nginx:mainline
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs
      - ./admin-app/app:/code/admin-app
      - ./admin-app/nginx.conf:/etc/nginx/conf.d/admin-app.conf
    networks:
      admin_network:
        aliases:
          - admin.local
          - www.admin.local
    depends_on:
      - admin_app

  # Memcached instance for PHP applications
  cache:
    image: memcached
    ports:
      - 11212:11211
    networks:
      - admin_network

  # Redis database
  redis:
    image: redis:alpine
    ports:
      - 7001:6379
    networks:
      - admin_network

  # MySQL database
  db:
    image: mysql:8
    command:
      - "--default-authentication-plugin=mysql_native_password"
    restart: always
    container_name: admin_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33062:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    networks:
      - admin_network
